name: Install Python with uv

inputs:
  python-version:
    description: Python version
    required: true

runs:
  using: composite
  steps:
    - name: Install uv
      # Install latest uv version using the installer
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Pin Python Version
      run: |
        export PYTHONUNBUFFERED=True
        uv python pin ${{ inputs.python-version }}
      shell: bash

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-python-${{ inputs.python-version }}-uv
      shell: bash

    - name: Install Dependencies
      run: uv sync
      shell: bash
