default_stages: [commit]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
    - id: ruff
      name: ruff
      description: "Run 'ruff' for extremely fast Python linting"
      args: [ --fix ]

    - id: ruff-format
      name: ruff-format
      description: "Run 'ruff format' for extremely fast Python formatting"
