name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rye
        run: |
          cd /opt
          curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
          source "/opt/rye/env"

      - name: Set Rye Config
        run: |
          rye config --set-bool behavior.global-python=true
          rye config --set-bool behavior.use-uv=true

      - name: Set up Python ${{ matrix.python-version }}
        run: |
          rye pin ${{ matrix.python-version }}
          rye sync

      - name: Pytest
        run: rye run pytest -s
